# Generated by Django 5.0.6 on 2025-03-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userbooks_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userbooks',
        ),
    ]
