# Generated by Django 5.0.6 on 2025-03-12 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_usercart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(null=True)),
                ('order_id', models.CharField(max_length=250, null=True, unique=True)),
                ('payment_id', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userbooks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.userbooks')),
            ],
        ),
    ]
