# Generated by Django 5.0.6 on 2025-03-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='userbooks',
        ),
        migrations.AddField(
            model_name='payment',
            name='userbooks',
            field=models.ManyToManyField(to='myapp.userbooks'),
        ),
    ]
