# Generated by Django 5.0.6 on 2025-03-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_payment_userbooks_payment_userbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='userbooks',
            field=models.ManyToManyField(to='myapp.usercart'),
        ),
    ]
