# Generated by Django 5.0.6 on 2025-03-13 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_payment_userbooks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='userbooks',
        ),
        migrations.AddField(
            model_name='payment',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.book'),
        ),
    ]
