# Generated by Django 5.0.6 on 2025-03-14 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_payment_userbooks_payment_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.userbooks'),
        ),
        migrations.AlterField(
            model_name='userbooks',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
