# Generated by Django 5.0.6 on 2025-03-14 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_payment_user_book_alter_userbooks_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbooks',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='usercart',
            name='quantity',
        ),
    ]
