# Generated by Django 5.0.6 on 2025-03-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_userbooks_quantity_remove_usercart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='other_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
