# Generated by Django 5.0.6 on 2025-03-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_book_other_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_file',
            field=models.FileField(null=True, upload_to='media/book_file/'),
        ),
    ]
