# Generated by Django 5.0.6 on 2025-04-01 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_bookpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBookProgress',
        ),
    ]
