# Generated by Django 5.0.6 on 2025-04-01 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_delete_userbookprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDFDocument',
        ),
    ]
