# Generated by Django 5.0.6 on 2025-04-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_delete_pdfdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_file2',
            field=models.FileField(blank=True, null=True, upload_to='private_books/'),
        ),
    ]
