# Generated by Django 5.0.6 on 2025-04-02 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_book_book_file2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_file2',
        ),
    ]
