# Generated by Django 5.2 on 2025-04-12 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_categories_book_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
